#!/usr/bin/env bash
# Bash script that redirects to another page

sudo apt-get -y install nginx
sudo service nginx restart
sed -i "41i error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
sudo service nginx restart
