#!/usr/bin/env bash
# Configures domain zone, subdomain www points to the load-balancer
# shellcheck disable=SC2086

subdomains=(www lb-01 web-01 web-02)

if [ -z "$2" ]
    then
        for s_dom in "${subdomains[@]}"
        do
            dig "${s_dom}.$1" | awk -v s_dom="$s_dom" '/ANSWER SECTION:/ {
                                                       getline; print "The subdomain",
                                                       s_dom,"is a",$4,
                                                       "record and points to",$5}'
        done
else
    dig "$2.$1" | awk -v s_dom="$2" '/ANSWER SECTION:/ {getline; print "The subdomain",
                                     s_dom,"is a",$4,"record and points to",$5}'
fi
