#!/usr/bin/env bash
# script that configures a new Ubuntu machine

apt-get update
apt-get -y install nginx
sudo service nginx restart
sudo sed -i "22 i \ add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
