#!/usr/bin/env bash
# script that installs load balancer

sudo apt-get install software-property-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6
sudo apt-get update
sudo apt-get install haproxy
