#!/usr/bin/env bash
#script that generates a MySQL dump and creates a compressed archive out of it

NOW=$(date +%d-%m-%Y)
mysqldump -u root -p"$1" --all-databases > backup.sql
tar --gzip -cf "$NOW".tar.gz backup.sql
