#!/usr/bin/env bash
# deletes old symlink, creates new one, and restarts

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
