#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times

COUNTER=0
while [ $COUNTER -le 9 ];
do
	if (( COUNTER == "9" )); then
		echo "Hi"
	fi
	echo "Holberton School"
	COUNTER=$(( COUNTER + 1 )) #increments counter
done
