#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times

COUNTER=1
while [ $COUNTER -le 20 ];
do
	echo "$COUNTER"
	if (( COUNTER == "4" )); then
		echo "bad luck from China"
	elif (( COUNTER == "9" )); then
		echo "bad luck from Japan"
	elif (( COUNTER == "17" )); then
		echo "bad luck from Italy"
	fi
	COUNTER=$(( COUNTER + 1 )) #increments counter
done
