#!/usr/bin/env bash
# Bash script that displays bad luck number of 3 countries

COUNTER=1
while [ $COUNTER -le 20 ];
do
	echo "$COUNTER"
case $COUNTER in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
esac
	(( COUNTER++ )) #increments counter
done
