#!/usr/bin/env bash
# Bash script that gives information about the
# holbertonschool file

for file in holbertonschool;
do
	if [ -e $file ]; then
		echo "holbertonschool file exists"
		if [ -s $file ]; then
			echo "$file file is not empty"
		else
			echo "$file file is empty"
		fi
		if [ -f $file ]; then
			echo "holbertonschool is a regular file"
		fi
	else
		echo "holbertonschool file does not exist"
	fi
done
